resolver: nightly-2020-01-05
packages:
- .
- hie-plugin-api

extra-deps:
# - ./submodules/HaRe
- git: https://github.com/Avi-D-coder/ormolu
  commit: 721952c892f7f22ac84cd262e0d0f8906e2ae89b
- git: https://github.com/Avi-D-coder/hlint
  commit: b50d9cf08e409d4ca20abf37fb541baebff60391

- apply-refact-0.7.0.0
- bytestring-trie-0.2.5.0
- cabal-helper-1.0.0.0
- clock-0.7.2
- constrained-dynamic-0.1.0.0
- floskell-0.10.2
- fold-debounce-0.2.0.9
- haddock-api-2.23.0
- haddock-library-1.8.0
- hie-bios-0.3.2
- hoogle-5.0.17.11
- hsimport-0.11.0
- semigroups-0.18.5
- temporary-1.2.1.1
- haskell-src-exts-1.21.1
- ilist-0.3.1.0
- monad-dijkstra-0.1.1.2
allow-newer: true

flags:
  haskell-ide-engine:
    pedantic: true
  hie-plugin-api:
    pedantic: true


# allow-newer: true

nix:
  packages: [ icu libcxx zlib ]

concurrent-tests: false
