resolver: nightly-2019-11-07
packages:
- .
- hie-plugin-api

extra-deps:
- ./hie-bios
- ./submodules/HaRe
- ./submodules/cabal-helper
- ./submodules/ghc-mod/ghc-project-types
- ./submodules/cabal/hackage-security/hackage-security
- ./submodules/apply-refact
- bytestring-trie-0.2.5.0
- constrained-dynamic-0.1.0.0
- fclabels-2.0.3.3
- fold-debounce-0.2.0.9
- haddock-api-2.23.0
- haddock-library-1.8.0
- haskell-lsp-0.17.0.0
- hoogle-5.0.17.12
- hsimport-0.11.0
- hslogger-1.3.1.0
- syz-0.2.0.0
- Strafunski-StrategyLib-5.0.1.0
- monad-dijkstra-0.1.1.2
- network-bsd-2.8.1.0

flags:
  haskell-ide-engine:
    pedantic: true
  hie-plugin-api:
    pedantic: true


# allow-newer: true

nix:
  packages: [ icu libcxx zlib ]

concurrent-tests: false
