resolver: nightly-2020-01-17
packages:
- .
- hie-plugin-api

extra-deps:
# - ./submodules/HaRe
- git: https://github.com/ndmitchell/hlint.git
  commit: 5f267eb873e349fc010a4a0da7778211853b6f03

- apply-refact-0.7.0.0
- bytestring-trie-0.2.5.0
- cabal-helper-1.0.0.0
- clock-0.7.2
- constrained-dynamic-0.1.0.0
- floskell-0.10.2
- haddock-api-2.23.0
- haddock-library-1.8.0
- hie-bios-0.3.2
- hoogle-5.0.17.14
- hsimport-0.11.0
- semigroups-0.18.5
- temporary-1.2.1.1
- ilist-0.3.1.0
- monad-dijkstra-0.1.1.2

flags:
  haskell-ide-engine:
    pedantic: true
  hie-plugin-api:
    pedantic: true


allow-newer: true

nix:
  packages: [ icu libcxx zlib ]

concurrent-tests: false
